export interface FeaturedProject {
	name: string;
	href: string;
	imageSrc: string;
	description: string;
	longDescription: string[];
}

export const tooltips = {
	carousel: 'Swipe to browse',
	allProjects: "Click on a project's name to view its GitHub page.",
};

export const fallbackDescription = 'This project does not have a description.';

export const featuredProjects: FeaturedProject[] = [
	{
		name: 'Beings of Habit',
		href: 'https://github.com/adidoesnt/beingsofhabit',
		imageSrc: '/boh-logo.svg',
		description: 'A holistic health and wellness platform exploring fitness, nutrition and well-being.',
		longDescription: [
			'Being of Habit is a holistic health and wellness platform that aims to explore 3 central pillars of life: fitness, nutrition and well-being. It was conceptualised by my girlfriend Ishita, aiming to explore the latest in the health and wellness space, drawing inspiration from evidence-based podcasts, books, publications, social media and more.',
			"The platform was originally created using SquareSpace, which lacks the flexibility that Ishita wanted. As a result, we started rebuilding the platform using NextJS and TailwindCSS. Additionally, we created a simple CMS to allow the website's blog section to be managed easily.",
			'I also took this project as a learning opportunity; I explored potential technology stacks and analysed them to choose what I felt would be the best fit for the project. I also gained hands-on experience with AWS and Terraform, which I used to deploy our custom CMS.',
			'This project is currently in progress, but the GitHub repository can be found <a class="text-primary underline hover:opacity-70" href="https://github.com/adidoesnt/beingsofhabit" target="_blank" rel="noopener noreferrer">here</a>.',
		],
	},
	{
		name: 'EchoFinder',
		href: 'https://github.com/adidoesnt/echofinder',
		imageSrc: '/ef-logo.svg',
		description: 'A RAG-based chat history search engine, built as a Telegram bot.',
		longDescription: [
			'EchoFinder is a <b>RAG-based chat history search engine</b> that allows users to search for messages in a conversation, created in collaboration with my long-time friend and frequent collaborator Vishesh. It uses an embedding model to convert messages into vectors, which are then stored in a vector database. EchoFinder then performs a similarity search, allowing users to find messages that match their search prompt. It is primarily a Telegram Bot, but can also be self-hosted for use with WhatsApp.',
			'The Telegram and WhatsApp bots are built using NodeJS along with Node-Telegram-Bot-API and WhatsApp-Web.js, respectively. Embeddings are automatically generated by ChromaDB using all-MiniLM-L6-v2 before being stored in the vector database.',
			'Here is a link to the project\'s <a class="text-primary underline hover:opacity-70" href="https://github.com/adidoesnt/echofinder" target="_blank" rel="noopener noreferrer">GitHub repository</a>.',
		],
	},
	{
		name: 'TeleDr',
		href: 'https://github.com/adidoesnt/teledr',
		imageSrc: '/teledr-logo.svg',
		description: 'An LLM-based chat summarisation bot for Telegram and WhatsApp.',
		longDescription: [
			'TeleDR is an <b>LLM-based chat summarisation bot</b> that allows users to summarise the last <i>n</i> messages in a conversation. I created TeleDr alongside my friend Vishesh, with whom I collaborate quite frequently on various side-projects. Although TeleDR is intended for use with Telegram, it can also be self-hosted for use with WhatsApp.',
			'The Telegram bot is built with NodeJS and Node-Telegram-Bot-API. The WhatsApp bot is built with NodeJS and WhatsApp-Web.js. Summarisation is performed using LangChain and LLaMa3.',
			'Here is a link to the project\'s <a class="text-primary underline hover:opacity-70" href="https://github.com/adidoesnt/teledr" target="_blank" rel="noopener noreferrer">GitHub repository</a>.',
		],
	},
];
